import FWCore.ParameterSet.Config as cms

recoSelect = cms.VPSet(
    cms.PSet( name = cms.string( 'JPsi' ),
          ptMin = cms.double( 6.0 ),
         etaMax = cms.double( 10.0 ),
        massMin = cms.double( 1.50   ),
        massMax = cms.double( 5.50   ),
        probMin = cms.double( 0.002 ),
        constrMass  = cms.double( 3.096900 ),
        constrSigma = cms.double( 0.000006 )
    ),
    cms.PSet( name = cms.string( 'Lam0'  ),
          ptMin = cms.double( 3.0 ),
         etaMax = cms.double( 10.0 ),
        massMin = cms.double(  0.80  ),
        massMax = cms.double(  1.80  ),
        probMin = cms.double( 0.002 ),
        constrMass  = cms.double(  1.115683 ),
        constrSigma = cms.double( -1.0 )
    ),
    cms.PSet( name = cms.string( 'LbToLam0' ),
        mPsiMin = cms.double( 3.0819 ),
        mPsiMax = cms.double( 3.1119 ),
        mLam0Min= cms.double( 1.095 ),
        mLam0Max= cms.double( 1.135 ),
        massMin = cms.double( 5.00 ),
        massMax = cms.double( 7.00 ),
        probMin = cms.double( 0.002 ),
        massFitMin = cms.double( 5.00 ),
        massFitMax = cms.double( 6.00 ),
        constrMJPsi = cms.bool( True )
    ),
    cms.PSet( name = cms.string( 'LbToTkTk' ),
        mPsiMin = cms.double( 3.0819 ),
        mPsiMax = cms.double( 3.1119 ),
          ptMin = cms.double( 3.0  ),
         etaMax = cms.double( 10.0 ),
        massMin = cms.double( 5.00 ),
        massMax = cms.double( 7.00 ),
        probMin = cms.double( 0.002 ),
     massFitMin = cms.double( 5.00 ),
     massFitMax = cms.double( 6.00 ),
    constrMass  = cms.double( 3.0916 ),
    constrSigma = cms.double( 0.000006 ),
     #compCharge = cms.double( 0 )
    ),
)
